### ISSUE TITLE
Qt6 anki problem

### ISSUE THREAD

**Issue by yaoberh** [AustinHasten/AnkiRandomFont#5]
When using anki qt6 version I get this error:

```
When loading '⁨Randomize Fonts⁩':
⁨Traceback (most recent call last):
  File "/home/yaoberh/pyenv/lib/python3.10/site-packages/aqt/addons.py", line 239, in loadAddons
    __import__(addon.dir_name)
  File "/home/yaoberh/.local/share/Anki2/addons21/1603486068/__init__.py", line 212, in <module>
    allInstalledFonts = QFontDatabase().families()
TypeError: QFontDatabase(QFontDatabase): not enough arguments
```

**Comment by yaoberh** [comment]
Changing ``QFontDatabase().families()`` to `QFontDatabase::families()` as per qt6 changes returns this error:

```
When loading '⁨Randomize Fonts⁩':
⁨Traceback (most recent call last):
  File "/home/yaoberh/pyenv/lib/python3.10/site-packages/aqt/addons.py", line 239, in loadAddons
    __import__(addon.dir_name)
  File "/home/yaoberh/.local/share/Anki2/addons21/1603486068/__init__.py", line 212
    allInstalledFonts = QFontDatabase::families()
                                     ^
SyntaxError: invalid syntax
```

**Comment by AustinHasten** [comment]
It looks like it's no longer necessary to instantiate a QFontDatabase object as of Qt6:
https://doc.qt.io/archives/qt-6.0/qfontdatabase-obsolete.html

Try `QFontDatabase.families()`

**Comment by yaoberh** [comment]
That seems to have solved that line, but now I'm getting an error in the next one:

```
When loading '⁨Randomize Fonts⁩':
⁨Traceback (most recent call last):
  File "/home/yaoberh/pyenv/lib/python3.10/site-packages/aqt/addons.py", line 239, in loadAddons
    __import__(addon.dir_name)
  File "/home/yaoberh/.local/share/Anki2/addons21/1603486068/__init__.py", line 213, in <module>
    defaultFont = QFontDatabase().systemFont(QFontDatabase.GeneralFont).family()
TypeError: QFontDatabase(QFontDatabase): not enough arguments
```

**Comment by AustinHasten** [comment]
Looks like we'll also need to remove the parens on that same line. So:

`QFontDatabase.systemFont(QFontDatabase.GeneralFont).family()`

**Comment by yaoberh** [comment]
```
  File "/home/yaoberh/pyenv/lib/python3.10/site-packages/aqt/addons.py", line 239, in loadAddons
    __import__(addon.dir_name)
  File "/home/yaoberh/.local/share/Anki2/addons21/1603486068/__init__.py", line 215, in <module>
    refreshConfig()
  File "/home/yaoberh/.local/share/Anki2/addons21/1603486068/__init__.py", line 144, in refreshConfig
    for font in QFontDatabase.families(wsValue):
TypeError: families(writingSystem: QFontDatabase.WritingSystem = QFontDatabase.Any): argument 1 has unexpected type 'int'
```

**Comment by AustinHasten** [comment]
Looks like WritingSystems used to be their own special class but now they're just python built-in enums. I don't have Anki Qt6 installed so I can't test myself, but I think we would need to update the line to be:

`for font in QFontDatabase.WritingSystem[wsName];`

**Comment by yaoberh** [comment]
Getting this error now :(

```
  File "/home/yaoberh/pyenv/lib/python3.10/site-packages/aqt/addons.py", line 239, in loadAddons
    __import__(addon.dir_name)
  File "/home/yaoberh/.local/share/Anki2/addons21/1603486068/__init__.py", line 215, in <module>
    refreshConfig()
  File "/home/yaoberh/.local/share/Anki2/addons21/1603486068/__init__.py", line 144, in refreshConfig
    for font in QFontDatabase.WritingSystem[wsName]:
TypeError: 'WritingSystem' object is not iterable
```

**Comment by AustinHasten** [comment]
Oops, I think it might actually be

`for font in QFontDatabase.families(QFontDatabase.WritingSystem[wsName]):`

Thanks for testing this out and troubleshooting with me.

**Comment by yaoberh** [comment]
Error's jumping to another area now haha

```
File "/home/yaoberh/pyenv/lib/python3.10/site-packages/aqt/addons.py", line 239, in loadAddons
    __import__(addon.dir_name)
  File "/home/yaoberh/.local/share/Anki2/addons21/1603486068/__init__.py", line 217, in <module>
    addAllHooks()
  File "/home/yaoberh/.local/share/Anki2/addons21/1603486068/__init__.py", line 170, in addAllHooks
    addHook(language, enabledfonts)
  File "/home/yaoberh/.local/share/Anki2/addons21/1603486068/__init__.py", line 158, in addHook
    hook = createRandomizer(f'random{language}', fonts)
  File "/home/yaoberh/.local/share/Anki2/addons21/1603486068/__init__.py", line 122, in createRandomizer
    fonts = [defaultFont]
NameError: name 'defaultFont' is not defined
```

**Comment by AustinHasten** [comment]
I think we just need parens after systemFont on that line.

**Comment by yaoberh** [comment]
```
  File "/home/yaoberh/pyenv/lib/python3.10/site-packages/aqt/addons.py", line 239, in loadAddons
    __import__(addon.dir_name)
  File "/home/yaoberh/.local/share/Anki2/addons21/1603486068/__init__.py", line 213, in <module>
    defaultFont = QFontDatabase.systemFont().family
TypeError: systemFont(QFontDatabase.SystemFont): not enough arguments
```

**Comment by AustinHasten** [comment]
I guess we need QFontDatabase.GeneralFont in the parenthesis after systemFont.

**Comment by yaoberh** [comment]
Yep! Anki starts with no errors now. Although it still throws this error in preview and Cards:
![image](https://user-images.githubusercontent.com/30667087/145911623-ae9395d2-8abd-4b2d-af19-9c2d87f98a01.png)
![Peek 2021-12-13 21-43](https://user-images.githubusercontent.com/30667087/145912004-fafcae8f-4b83-4b7b-b520-47f8b4e003b3.gif)

**Comment by AustinHasten** [comment]
That one has me a little stumped so I'll grab Anki qt6 and do some testing of my own

**Comment by AustinHasten** [comment]
[__init__.zip](https://github.com/AustinHasten/AnkiRandomFont/files/7713198/__init__.zip)

Not sure how this differs than what you have but this one is working for me.

**Comment by yaoberh** [comment]
Working! :dancers:
